import { DailyEntry, Action, Badge, Insight } from "../types";

export const MOCK_HISTORY: DailyEntry[] = [
  {
    id: "entry-mon",
    userId: "anish-123",
    date: "2026-06-15", // Monday
    travel: { mode: "car", distance: 15, trips: 2 },
    food: { mealType: "chicken", delivery: true },
    energy: { acHours: 4, fanHours: 8, lightsUsage: 6, devicesCharged: 3, usageStyle: "moderate" },
    shopping: { type: "small-online" },
    waste: { reusableBottle: false, plasticBottleBought: true, reusableBagUsed: false, foodWaste: true, recyclingDone: false },
    totalCO2e: 9.2,
    greenScore: 40,
  },
  {
    id: "entry-tue",
    userId: "anish-123",
    date: "2026-06-16", // Tuesday
    travel: { mode: "cab", distance: 10, trips: 2 },
    food: { mealType: "vegetarian", delivery: false },
    energy: { acHours: 3, fanHours: 6, lightsUsage: 5, devicesCharged: 2, usageStyle: "moderate" },
    shopping: { type: "none" },
    waste: { reusableBottle: true, plasticBottleBought: false, reusableBagUsed: true, foodWaste: false, recyclingDone: true },
    totalCO2e: 7.8,
    greenScore: 49,
  },
  {
    id: "entry-wed",
    userId: "anish-123",
    date: "2026-06-17", // Wednesday
    travel: { mode: "bike", distance: 12, trips: 3 },
    food: { mealType: "dairy-heavy", delivery: true },
    energy: { acHours: 5, fanHours: 8, lightsUsage: 6, devicesCharged: 4, usageStyle: "high" },
    shopping: { type: "clothing" },
    waste: { reusableBottle: true, plasticBottleBought: false, reusableBagUsed: true, foodWaste: false, recyclingDone: false },
    totalCO2e: 8.5,
    greenScore: 45,
  },
  {
    id: "entry-thu",
    userId: "anish-123",
    date: "2026-06-18", // Thursday
    travel: { mode: "metro", distance: 20, trips: 2 },
    food: { mealType: "vegan", delivery: false },
    energy: { acHours: 1, fanHours: 5, lightsUsage: 4, devicesCharged: 2, usageStyle: "low" },
    shopping: { type: "none" },
    waste: { reusableBottle: true, plasticBottleBought: false, reusableBagUsed: true, foodWaste: false, recyclingDone: true },
    totalCO2e: 5.9,
    greenScore: 62,
  },
  {
    id: "entry-fri",
    userId: "anish-123",
    date: "2026-06-19", // Friday
    travel: { mode: "car", distance: 8, trips: 2 },
    food: { mealType: "vegetarian", delivery: true },
    energy: { acHours: 2, fanHours: 6, lightsUsage: 5, devicesCharged: 3, usageStyle: "moderate" },
    shopping: { type: "none" },
    waste: { reusableBottle: true, plasticBottleBought: false, reusableBagUsed: true, foodWaste: false, recyclingDone: true },
    totalCO2e: 7.1,
    greenScore: 54,
  },
  {
    id: "entry-sat",
    userId: "anish-123",
    date: "2026-06-20", // Saturday
    travel: { mode: "cycle", distance: 5, trips: 2 },
    food: { mealType: "vegetarian", delivery: false },
    energy: { acHours: 2, fanHours: 10, lightsUsage: 8, devicesCharged: 4, usageStyle: "low" },
    shopping: { type: "reused" },
    waste: { reusableBottle: true, plasticBottleBought: false, reusableBagUsed: true, foodWaste: false, recyclingDone: true },
    totalCO2e: 6.4,
    greenScore: 58,
  },
  {
    id: "entry-sun",
    userId: "anish-123",
    date: "2026-06-21", // Sunday
    travel: { mode: "walk", distance: 3, trips: 1 },
    food: { mealType: "vegan", delivery: false },
    energy: { acHours: 0, fanHours: 4, lightsUsage: 4, devicesCharged: 2, usageStyle: "low" },
    shopping: { type: "none" },
    waste: { reusableBottle: true, plasticBottleBought: false, reusableBagUsed: true, foodWaste: false, recyclingDone: true },
    totalCO2e: 4.8,
    greenScore: 69,
  },
];

export const MOCK_ACTIONS: Action[] = [
  {
    id: "act-1",
    title: "Walk/Cycle for trips under 2 km",
    category: "travel",
    difficulty: "Easy",
    estimatedCarbonSaved: 0.8,
    estimatedMoneySaved: 50,
    completed: false,
  },
  {
    id: "act-2",
    title: "Use metro instead of bike or car",
    category: "travel",
    difficulty: "Medium",
    estimatedCarbonSaved: 2.2,
    estimatedMoneySaved: 120,
    completed: true,
  },
  {
    id: "act-3",
    title: "Avoid one food delivery",
    category: "food",
    difficulty: "Easy",
    estimatedCarbonSaved: 0.5,
    estimatedMoneySaved: 150,
    completed: true,
  },
  {
    id: "act-4",
    title: "Use reusable water bottle all day",
    category: "waste",
    difficulty: "Easy",
    estimatedCarbonSaved: 0.3,
    estimatedMoneySaved: 40,
    completed: true,
  },
  {
    id: "act-5",
    title: "Keep AC at 25°C or higher",
    category: "energy",
    difficulty: "Easy",
    estimatedCarbonSaved: 1.1,
    estimatedMoneySaved: 80,
    completed: true,
  },
  {
    id: "act-6",
    title: "Compost food waste",
    category: "waste",
    difficulty: "Easy",
    estimatedCarbonSaved: 0.8,
    estimatedMoneySaved: 0,
    completed: false,
  },
  {
    id: "act-7",
    title: "Buy thrifted or secondhand clothing",
    category: "shopping",
    difficulty: "Medium",
    estimatedCarbonSaved: 4.0,
    estimatedMoneySaved: 800,
    completed: false,
  },
];

export const MOCK_BADGES: Badge[] = [
  {
    id: "badge-first",
    title: "First Step",
    description: "Completed your very first carbon reduction action",
    icon: "Footprint",
    unlocked: true,
    unlockedAt: "2026-06-16",
  },
  {
    id: "badge-commute",
    title: "Smart Commuter",
    description: "Used public transport twice in a week",
    icon: "TrainFront",
    unlocked: true,
    unlockedAt: "2026-06-18",
  },
  {
    id: "badge-low",
    title: "Low Carbon Day",
    description: "Emissions fell below 5.0 kg CO2e in a single day",
    icon: "Sparkles",
    unlocked: true,
    unlockedAt: "2026-06-21",
  },
  {
    id: "badge-nodelivery",
    title: "No-Delivery Streak",
    description: "Avoided food delivery for 3 days in a row",
    icon: "ChefHat",
    unlocked: false,
  },
  {
    id: "badge-reuse",
    title: "Reuse Hero",
    description: "Used reusable bag and bottle for 7 consecutive days",
    icon: "ShieldCheck",
    unlocked: false,
  },
];

export const MOCK_SIMULATOR_SCENARIOS = [
  {
    id: "sim-1",
    title: "Short Distance Commute",
    category: "travel",
    currentLabel: "Cab/Car ride (6 km)",
    currentCo2: 1.5,
    currentMoney: 180,
    betterLabel: "Metro + Walk (6 km)",
    betterCo2: 0.24,
    betterMoney: 30,
    explanation: "Cabs are heavily carbon-intensive. Opting for a metro ride saves significant emissions and lowers travel costs.",
  },
  {
    id: "sim-2",
    title: "Dinner Choice",
    category: "food",
    currentLabel: "Ordered Beef/Red Meat Burger",
    currentCo2: 8.0,
    currentMoney: 280,
    betterLabel: "Home Cooked Vegan Meal",
    betterCo2: 1.5,
    betterMoney: 80,
    explanation: "Red meat has massive emission footprints from ranching. A plant-based meal reduces footprint by 80%.",
  },
  {
    id: "sim-3",
    title: "Climate Control",
    category: "energy",
    currentLabel: "AC run at 19°C (5 hrs)",
    currentCo2: 6.0,
    currentMoney: 150,
    betterLabel: "AC run at 25°C + Fan (3 hrs)",
    betterCo2: 2.4,
    betterMoney: 60,
    explanation: "Running the AC at high power and very low temperatures is highly inefficient. 25°C uses up to 40% less energy.",
  },
  {
    id: "sim-4",
    title: "Shopping Habits",
    category: "shopping",
    currentLabel: "Fast Fashion Brand New T-Shirt",
    currentCo2: 6.0,
    currentMoney: 799,
    betterLabel: "Thrift Store Vintage Shirt",
    betterCo2: 0.5,
    betterMoney: 250,
    explanation: "Manufacturing new garments uses immense water and dyeing energy. Circular shopping avoids 90% of those supply chain emissions.",
  },
];
